### ISSUE TITLE
using muon instead of meson

### ISSUE THREAD

**Issue by vtorri** [davea42/libdwarf-code#276]
[muon](https://muon.build/) is a C99 port of meson. Hence is quite faster than meson
It is available in msys2, package name : `muon`
in ubuntu, the package is called `muon-meson`

**Comment by vtorri** [comment]
note that `muon` also have a `ninja`-like implementation based on [samurai](https://github.com/michaelforney/samurai)

to compile libdwarf, just install `muon` and run:

```
muon.exe setup builddir
muon.exe -C builddir samu
```

**Comment by vtorri** [comment]
example of msys2 CI with muon:

```
name: msys2muon

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
 msys2_muonn:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      PYTHONIOENCODING: "utf-8"
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel git  mingw-w64-x86_64-toolchain mingw-w64-x86_64-muon mingw-w64-x86_64-zlib mingw-w64-x86_64-doxygen
    - name: Build libdwarf
      run: |
        muon setup --default-library shared -Ddwarfexample=true -Ddwarfgen=false builddir
        muon.exe -C builddir samu
        muon.exe -C builddir install
        muon.exe -C builddir test
```

less packages to install, faster configuration. Compilation will mainly have no performance improvements, though. You can try it and see the time spent to achieve these tests, compared to the msys2 meson CI
